#include <iostream>
#include <cstdlib>
#include <stdexcept>

// コンストラクタでthrowすると
// グローバルなインスタンスが作れない
// (もちろんポインタはいいけど)
//
// 結局コンストラクタでthrowしてもいいのか
// しないほうがいいのか迷う・・

class Foo {
public:
    Foo() {
        throw std::exception();
    }
};

// Foo global;    // NO!!!

int main( int argc, char *argv[] )
{
    try {
        Foo foo;
    } catch( std::exception& e ) {
        std::cerr << "caught exception" << std::endl;
    }


    return EXIT_SUCCESS;
}


